### ISSUE TITLE
-output json 'select * from a' causes too many json fields to be included

### ISSUE THREAD

**Issue by MatrixManAtYrService** [dbohdan/sqawk#13]
I have a command:

```
❯ ./table.sh
foo	bar
1	a
2	b
```

I pipe it to swawk and get the output that I want if I name the fields explicitly, like so:
```
❯ ./table.sh | sqawk -output json 'select foo, bar from a where bar = "b"' header=1
[{"foo":"2","bar":"b"}]
```

But if I `select *` I get many other fields too:
```
❯ ./table.sh | sqawk -output json 'select * from a where bar = "b"' header=1
 [{"anr":"2","anf":"2","a0":"2\tb","foo":"2","bar":"b","a3":"","a4":"","a5":"","a6":"","a7":"","a8":"","a9":"","a10":""}]
```

As a workaround I can delete those fields explicitly:
```
❯ ./table.sh | sqawk -output json 'select * from a where bar = "b"' header=1 | jq 'map(del(.a0, .a1, .a2, .a3, .a4, .a5, .a6, .a7, .a8, .a9, .a10, .anr, .anf))'
[
  {
    "foo": "2",
    "bar": "b"
  }
]
```
But I think it would be cleaner if I could tell sqawk to not include them in the first place.  Is there such a way?  If not, can there be?

**Comment by dbohdan** [comment]
There is no direct way to do it right now.  Standard SQL and SQLite 3's dialect do not allow you to select all columns except for a few, and Sqawk does not have its own functionality for it.  One thing you can do is limit the number of fields and disable the zeroth field.

```sh
$ ./table.sh | sqawk -output json,indent=1 'select * from a where bar = "b"' header=true F0=false NF=2
[{
    "anr" : "2",
    "anf" : "2",
    "foo" : "2",
    "bar" : "b"
}]
```

Then you will only need to delete `.anr` and `.anf` in jq rather than a varying number of fields.  Alternatively, you can delete all fields with the default name using a jq filter like

```
map(
  del(.anf, .anr)
  | to_entries
  | map(select(.key | test("^a\\d+$") | not))
  | from_entries
)
```

I would like to implement a feature for this eventually because there is no easy way to filter `-output table`.  It would be better to have it as an SQL extension rather than a per-file option.  If I do implement it I'll respond here to let you know.

**Comment by MatrixManAtYrService** [comment]
Thanks for the quick response.  I figured I was overlooking something.  Also, your jq expression is better than mine, so I'll use that for now.

**Comment by MatrixManAtYrService** [comment]
@dbohdan I thought I'd share what I was up to because I think it might make a reasonable addition to sqawk.  I'm glad to have gotten to know sqawk in the the process--for I'll surely use it separately--but I was going for generic transforms from tabular to json:

https://gist.github.com/MatrixManAtYrService/f00c9f7a9be9ee007faebe3cefb21880

Anyhow, thanks again for this tool.  I've been using vim macros to process mysql output--this is really gonna help my workflow.

**Comment by dbohdan** [comment]
You're welcome!  I agree this is a reasonable feature and I understand where you'd use it.  I am not rushing to implement it because doing it my preferred way is complicated and requires experimentation; I don't want to add specialized pre-file options if I can avoid it.  That said, if other ways prove impractical out I'll probably add it as a pre-file option like `without=1,3-4`.
