### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by jungle-boogie** [dbohdan/sqawk#4]
Hello,

Updated sqawk this morning, but the tests are failing--all of them:
https://gist.github.com/jungle-boogie/ac7b7d410375466120b8

**Comment by jungle-boogie** [comment]
This commit seemed to have fixed it:
https://github.com/dbohdan/sqawk/commit/1f6d0d0ff7c0aa3e6b2d3686b7d2e8b9958beaf6

Was that the intention or a side-effect?

**Comment by dbohdan** [comment]
Hi! The commit was intended to fix it. I mistakenly commented [on the gist](https://gist.github.com/jungle-boogie/ac7b7d410375466120b8#gistcomment-1563684) instead of here when asking you to try it out. Sorry about that. If Sqawk works for you now I will close the issue.

**Comment by jungle-boogie** [comment]
Hello @dbohdan,

Oh, I missed that comment of the gist.

Yes, you fixed it!

I'm sure you already know but you skipped v0.12.X with your releases.

**Comment by dbohdan** [comment]
Right. I skipped it on purpose because you really needed the `trim` option if you wanted to parse the output of commands like `ps` and convert it to tables. Without `trim=left` your header row would end up skewed. However, v0.12.0 would have been bug-free, so maybe I shouldn't skip releases. :-)

Since v0.13.1 works I'm closing this issue.
